const APP_DATA = {
    "formula 1": {
        "news": [
            {
                "id": 1,
                "title": "MAX VERSTAPPEN EMEKLİ OLMAYI DÜŞÜNÜYOR!",
                "cat": "formula 1",
                "date": "2026-03-29",
                "content": "Dört kez dünya şampiyonu olan Max Verstappen, 2026 teknik regülasyonlarına yönelik artan memnuniyetsizliğini dile getirirken, Japonya Grand Prix'sinin ardından F1 geleceği ile ilgili birçok şeyi düşünmesi gerektiğini söylemişti.",
                "img": "Resimler/Formula 1 Haberler/max-verstappen-red-bull-racing (1).jpg"
            },
            {
                "id": 2,
                "title": "FERRARI HAMLESİYLE HİBRİT AÇIĞI KAPATILDI!",
                "cat": "formula 1",
                "date": "2026-04-14",
                "content": "Ferrari’nin FIA nezdindeki girişimi sonuç verdi ve FIA, Mercedes ile Red Bull Racing’in sıralama turlarında kullandığı tartışmalı hibrit yöntemini yasakladı.<br><br>Söz konusu sistemde takımlar, MGU-K ünitesini “teknik arıza” gerekçesiyle anlık kapatarak yönetmelikteki kademeli güç düşüşünü devre dışı bırakıyordu. Bu sayede tur sonuna kadar maksimum güçle devam eden araçlar, özellikle son sektörde 50-100 kW ekstra avantaj elde ediyordu.<br><br>Ancak bu yöntem sadece performans değil, güvenlik açısından da risk yarattı. Sistem kapatıldıktan sonra yaşanan ani yavaşlamalar, hızlı turdaki pilotlar için tehlikeli anlara neden oldu.<br><br>FIA’nın yeni teknik direktifine göre artık MGU-K sadece gerçek ve kanıtlanabilir arızalarda devre dışı bırakılabilecek. Performans amacı taşıyan her müdahale kural ihlali sayılacak ve telemetri verileriyle anlık olarak denetlenecek.<br><br>Bu karar, özellikle sıralama turlarında küçük farkların belirleyici olduğu dengeleri doğrudan etkileyebilir.",
                "img": "Resimler/Formula 1 Haberler/Hibrit.png"
            },
            {
                "id": 3,
                "title": "VERSTAPPEN’İN GELECEĞİ TEHLİKEDE: LAMBIASE’NİN AYRILIĞI RED BULL’U SARSTI!",
                "cat": "formula 1",
                "date": "2026-04-14",
                "content": "Max Verstappen’in kariyerindeki en kritik dönemeçlerden biri yaklaşırken, Gianpiero Lambiase cephesinden gelen haber Formula 1 dünyasında dengeleri sarsmış durumda. Red Bull’da yıllardır Verstappen’in yarış mühendisi olarak görev yapan ve “GP” lakabıyla tanınan Lambiase’nin, sözleşmesinin sona ermesinin ardından McLaren saflarına katılacak olması, sadece teknik bir transfer değil; aynı zamanda büyük bir kırılmanın habercisi olarak görülüyor.<br><br>Bu ayrılık, özellikle Verstappen’in geleceğiyle ilgili tartışmaların alevlendiği bir döneme denk gelmesi nedeniyle çok daha fazla anlam taşıyor. Hollandalı pilotun, Japonya Grand Prix’si sonrası yaptığı açıklamalarda Formula 1’e devam etme konusunda ciddi şüpheler taşıdığını belirtmesi zaten soru işaretlerini artırmıştı. Şimdi ise en güvendiği isimlerden birinin takımdan ayrılıyor olması, 2026 sonrası için Red Bull ihtimalini daha da zayıflatıyor.<br><br>Verstappen’in olası ayrılık senaryosunun arkasında yalnızca performans düşüşü yatmıyor. 2026’da yürürlüğe girecek yeni nesil hibrit güç üniteleri ve araç konsepti, pilotun uzun süredir eleştirdiği konuların başında geliyor. Daha fazla enerji geri kazanımı ve elektrik gücüne dayalı sistemlerin ön plana çıkması, Verstappen’in sürüş karakterine hitap etmeyen bir yapı olarak öne çıkıyor. Ancak takım içindeki değişim de en az teknik regülasyonlar kadar belirleyici bir faktör.<br><br>Son yıllarda Red Bull Racing içerisinde yaşanan ayrılıklar, bir dominasyon döneminin yavaş yavaş sona erdiğini gösteriyor. Takımın mimarlarından Adrian Newey’in ayrılığı, ardından sportif direktör Jonathan Wheatley’nin takımdan kopuşu ve şimdi de Lambiase’nin gidişi, Red Bull’un yapı taşlarının tek tek söküldüğünü ortaya koyuyor.<br><br>Bu süreçte dikkat çeken bir diğer detay ise McLaren’ın eski Red Bull kadrolarını adeta yeniden bir araya getirmesi. Lambiase, daha önce takımdan ayrılan mühendislerle tekrar aynı çatı altında buluşacak. Bu durum, sadece bir transfer zinciri değil, aynı zamanda güç dengesinin yavaş yavaş yer değiştirdiğinin de işareti olabilir.<br><br>Özetle, Lambiase’nin ayrılığı tek başına bir mühendis değişimi değil; Verstappen’in kariyer rotasını etkileyebilecek kadar büyük bir gelişme. Eğer Red Bull bu dağılma sürecini durduramazsa, Formula 1’in son yıllardaki en baskın hikayelerinden biri beklenenden çok daha erken sona erebilir.",
                "img": "Resimler/Formula 1 Haberler/GP ve Max.png"
            }
        ],
        "pilots": [
            { "id": "verstappen", "name": "Max Verstappen #3", "team": "Oracle Red Bull Racing", "titles": 4, "img": "Resimler/Formula 1 Pilot ve Takımlar/Max Verstappen.png" },
            { "id": "hadjar", "name": "Isack Hadjar #6", "team": "Oracle Red Bull Racing", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Isack Hadjar.png" },
            { "id": "hamilton", "name": "Lewıs Hamılton #44", "team": "Scuderia Ferrari HP", "titles": 7, "img": "Resimler/Formula 1 Pilot ve Takımlar/Lewis Hamilton.png" },
            { "id": "leclerc", "name": "Charles Leclerc #16", "team": "Scuderia Ferrari HP", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Charles Leclerc.png" },
            { "id": "norris", "name": "Lando Norrıs #1", "team": "McLaren Formula 1 Team", "titles": 1, "img": "Resimler/Formula 1 Pilot ve Takımlar/Lando Norris.png" },
            { "id": "piastri", "name": "Oscar Pıastrı #81", "team": "McLaren Formula 1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Oscar Piastri.png" },
            { "id": "russell", "name": "George Russell #63", "team": "Mercedes-AMG PETRONAS F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/George Russell.png" },
            { "id": "antonelli", "name": "Andrea Kımı Antonellı #12", "team": "Mercedes-AMG PETRONAS F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Andrea Kimi Antonelli.png" },
            { "id": "alonso", "name": "Fernando Alonso #14", "team": "Aston Martin Aramco F1 Team", "titles": 2, "img": "Resimler/Formula 1 Pilot ve Takımlar/Fernando Alonso.png" },
            { "id": "stroll", "name": "Lance Stroll #18", "team": "Aston Martin Aramco F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Lance Stroll.png" },
            { "id": "gasly", "name": "Pıerre Gasly #10", "team": "BWT Alpine F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Pierre Gasly.png" },
            { "id": "colapinto", "name": "Franco Colapınto #43", "team": "BWT Alpine F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Franco Colapinto.png" },
            { "id": "albon", "name": "Alexander Albon #23", "team": "Williams Racing", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Alexander Albon.png" },
            { "id": "sainz", "name": "Carlos Saınz Jr. #55", "team": "Williams Racing", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Carlos Sainz.png" },
            { "id": "lawson", "name": "Lıam Lawson #30", "team": "Visa Cash App RB F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Liam Lawson.png" },
            { "id": "lindblad", "name": "Arvıd Lındblad #41", "team": "Visa Cash App RB F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Arvid Lindblad.png" },
            { "id": "bearman", "name": "Olıver Bearman #87", "team": "Haas F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Oliver Bearman.png" },
            { "id": "ocon", "name": "Esteban Ocon #31", "team": "Haas F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Esteban Ocon.png" },
            { "id": "hulkenberg", "name": "Nıco Hulkenberg #27", "team": "Audi F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Nico Hulkenberg.png" },
            { "id": "bortoleto", "name": "Gabrıel Bortoleto #5", "team": "Audi F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Gabriel Bortoleto.png" },
            { "id": "bottas", "name": "Valtterı Bottas #77", "team": "Cadillac Formula 1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Valtteri Bottas.png" },
            { "id": "perez", "name": "Sergıo Pérez #11", "team": "Cadillac Formula 1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Sergio Perez.png" }
        ],
        "teams": [
            { "id": "redbull", "name": "Oracle Red Bull Racıng", "titles": 6, "img": "Resimler/Formula 1 Pilot ve Takımlar/Red Bull.png" },
            { "id": "ferrari", "name": "Scuderıa Ferrarı HP", "titles": 16, "img": "Resimler/Formula 1 Pilot ve Takımlar/Ferrari.png" },
            { "id": "mercedes", "name": "Mercedes-AMG PETRONAS F1 Team", "titles": 8, "img": "Resimler/Formula 1 Pilot ve Takımlar/Mercedes.png" },
            { "id": "mclaren", "name": "McLaren F1 Team", "titles": 10, "img": "Resimler/Formula 1 Pilot ve Takımlar/McLaren.png" },
            { "id": "aston", "name": "Aston Martın Aramco F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Aston Martin.png" },
            { "id": "alpine", "name": "BWT Alpıne F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Alpine.png" },
            { "id": "williams", "name": "Wıllıams Racıng", "titles": 9, "img": "Resimler/Formula 1 Pilot ve Takımlar/Williams.png" },
            { "id": "rb", "name": "Vısa Cash App RB F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/RB.png" },
            { "id": "haas", "name": "Haas F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Haas.png" },
            { "id": "audi", "name": "Audı F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Audi.png" },
            { "id": "cadillac", "name": "Cadıllac F1 Team", "titles": 0, "img": "Resimler/Formula 1 Pilot ve Takımlar/Cadillac.png" }
        ],
        "standings": {
            "pilots": [
                { "pos": 1, "name": "Andrea Kimi Antonelli #12", "team": "Mercedes-AMG PETRONAS F1 Team", "pts": 72 },
                { "pos": 2, "name": "George Russell #63", "team": "Mercedes-AMG PETRONAS F1 Team", "pts": 63 },
                { "pos": 3, "name": "Charles Leclerc #16", "team": "Scuderia Ferrari HP", "pts": 49 },
                { "pos": 4, "name": "Lewis Hamilton #44", "team": "Scuderia Ferrari HP", "pts": 41 },
                { "pos": 5, "name": "Lando Norris #1", "team": "McLaren F1 Team", "pts": 25 },
                { "pos": 6, "name": "Oscar Piastri #81", "team": "McLaren F1 Team", "pts": 21 },
                { "pos": 7, "name": "Oliver Berman #87", "team": "Haas F1 Team", "pts": 17 },
                { "pos": 8, "name": "Pierre Gasly #10", "team": "BWT Alpine F1 Team", "pts": 15 },
                { "pos": 9, "name": "Max Verstappen #3", "team": "Oracle Red Bull Racing", "pts": 12 },
                { "pos": 10, "name": "Liam Lawson #30", "team": "Visa Cash App RB F1 Team", "pts": 10 },
                { "pos": 11, "name": "Arvid Lindblad #41", "team": "Visa Cash App RB F1 Team", "pts": 4 },
                { "pos": 12, "name": "Isack Hadjar #6", "team": "Oracle Red Bull Racing", "pts": 4 },
                { "pos": 13, "name": "Gabriel Bortoleto #5", "team": "Audi F1 Team", "pts": 2 },
                { "pos": 14, "name": "Carlos Sainz Jr. #55", "team": "Williams Racing", "pts": 2 },
                { "pos": 15, "name": "Esteban Ocon #31", "team": "Haas F1 Team", "pts": 1 },
                { "pos": 16, "name": "Franco Colapinto #43", "team": "BWT Alpine F1 Team", "pts": 1 },
                { "pos": 17, "name": "Nico Hülkenberg #27", "team": "Audi F1 Team", "pts": 0 },
                { "pos": 18, "name": "Alexander Albon #23", "team": "Williams Racing", "pts": 0 },
                { "pos": 19, "name": "Valtteri Bottas #77", "team": "Cadillac F1 Team", "pts": 0 },
                { "pos": 20, "name": "Sergio Perez #11", "team": "Cadillac F1 Team", "pts": 0 },
                { "pos": 21, "name": "Fernando Alonso #14", "team": "Aston Martin Aramco F1 Team", "pts": 0 },
                { "pos": 22, "name": "Lance Stroll #18", "team": "Aston Martin Aramco F1 Team", "pts": 0 }
            ],
            "teams": [
                { "pos": 1, "name": "Mercedes-AMG PETRONAS F1 Team", "pts": 135 },
                { "pos": 2, "name": "Scuderia Ferrari HP", "pts": 90 },
                { "pos": 3, "name": "McLaren F1 Team", "pts": 46 },
                { "pos": 4, "name": "Haas F1 Team", "pts": 18 },
                { "pos": 5, "name": "BWT Alpine F1 Team", "pts": 16 },
                { "pos": 6, "name": "Oracle Red Bull Racing", "pts": 16 },
                { "pos": 7, "name": "Visa Cash App RB F1 Team", "pts": 14 },
                { "pos": 8, "name": "Audi F1 Team", "pts": 2 },
                { "pos": 9, "name": "Williams Racing", "pts": 2 },
                { "pos": 10, "name": "Cadillac F1 Team", "pts": 0 },
                { "pos": 11, "name": "Aston Martin Aramco F1 Team", "pts": 0 }
            ]
        },
        "calendar": [
            { "round": 1, "gp": "Australian Grand Prix", "country": "Avustralya", "date": "6-8 Mart", "track": "Melbourne", "isoDate": "2026-03-06", "status": "Tamamlandı" },
            { "round": 2, "gp": "Chinese Grand Prix", "country": "Çin", "date": "13-15 Mart", "track": "Shanghai", "isoDate": "2026-03-13", "status": "Tamamlandı" },
            { "round": 3, "gp": "Japanese Grand Prix", "country": "Japonya", "date": "27-29 Mart", "track": "Suzuka", "isoDate": "2026-03-27", "status": "Tamamlandı" },
            { "round": 4, "gp": "Bahrain Grand Prix", "country": "Bahreyn", "date": "10-12 Nisan", "track": "Sakhir", "isoDate": "2026-04-10", "status": "İptal" },
            { "round": 5, "gp": "Saudi Arabian Grand Prix", "country": "Suudi Arabistan", "date": "17-19 Nisan", "track": "Jeddah", "isoDate": "2026-04-17", "status": "İptal" },
            { "round": 6, "gp": "Miami Grand Prix", "country": "ABD", "date": "1-3 Mayıs", "track": "Miami", "isoDate": "2026-05-01", "status": "Sıradaki", "sessions": [{ "name": "Cuma: 1. Antrenman", "time": "19:30" }, { "name": "Cuma: Sprint Sıralama Turları", "time": "23:30" }, { "name": "Cumartesi: Sprint Yarışı", "time": "19:00" }, { "name": "Cumartesi: Ana Yarış Sıralama Turları", "time": "23:00" }, { "name": "Pazar: Yarış", "time": "23:00" }] },
            { "round": 7, "gp": "Emilia Romagna GP", "country": "İtalya", "date": "22-24 Mayıs", "track": "Imola", "isoDate": "2026-05-22", "status": "Bekliyor", "sessions": [{ "name": "Cuma: 1. Antrenman", "time": "19:30" }, { "name": "Cuma: Sprint Sıralama Turları", "time": "23:30" }, { "name": "Cumartesi: Sprint Yarışı", "time": "19:00" }, { "name": "Cumartesi: Ana Yarış Sıralama Turları", "time": "23:00" }, { "name": "Pazar: Yarış", "time": "23:00" }] },
            { "round": 8, "gp": "Monaco Grand Prix", "country": "Monako", "date": "05-07 Haziran", "track": "Monaco", "isoDate": "2026-06-05", "status": "Bekliyor" },
            { "round": 9, "gp": "Spanish Grand Prix", "country": "İspanya", "date": "12-14 Haziran", "track": "Barcelona-Catalunya", "isoDate": "2026-06-12", "status": "Bekliyor" },
            { "round": 10, "gp": "Austrian Grand Prix", "country": "Avusturya", "date": "26-28 Haziran", "track": "Red Bull Ring", "isoDate": "2026-06-26", "status": "Bekliyor" },
            { "round": 11, "gp": "British Grand Prix", "country": "İngiltere", "date": "03-05 Temmuz", "track": "Silverstone", "isoDate": "2026-07-03", "status": "Bekliyor" },
            { "round": 12, "gp": "Belgian Grand Prix", "country": "Belçika", "date": "17-19 Temmuz", "track": "Spa-Francorchamps", "isoDate": "2026-07-17", "status": "Bekliyor" },
            { "round": 13, "gp": "Hungarian Grand Prix", "country": "Macaristan", "date": "24-26 Temmuz", "track": "Hungaroring", "isoDate": "2026-07-24", "status": "Bekliyor" },
            { "round": 14, "gp": "Dutch Grand Prix", "country": "Hollanda", "date": "21-23 Ağustos", "track": "Zandvoort", "isoDate": "2026-08-21", "status": "Bekliyor" },
            { "round": 15, "gp": "Italian Grand Prix", "country": "İtalya", "date": "04-06 Eylül", "track": "Monza", "isoDate": "2026-09-04", "status": "Bekliyor" },
            { "round": 16, "gp": "Madrid Grand Prix", "country": "İspanya", "date": "11-13 Eylül", "track": "Madring", "isoDate": "2026-09-11", "status": "Bekliyor" },
            { "round": 17, "gp": "Azerbaijan Grand Prix", "country": "Azerbaycan", "date": "24-26 Eylül", "track": "Baku", "isoDate": "2026-09-24", "status": "Bekliyor" },
            { "round": 18, "gp": "Singapore Grand Prix", "country": "Singapur", "date": "9-11 Ekim", "track": "Marina Bay", "isoDate": "2026-10-09", "status": "Bekliyor" },
            { "round": 19, "gp": "United States Grand Prix", "country": "ABD", "date": "23-25 Ekim", "track": "Austin", "isoDate": "2026-10-23", "status": "Bekliyor" },
            { "round": 20, "gp": "Mexican Grand Prix", "country": "Meksika", "date": "30 Ekim-1 Kasım", "track": "Mexico City", "isoDate": "2026-10-30", "status": "Bekliyor" },
            { "round": 21, "gp": "São Paulo Grand Prix", "country": "Brezilya", "date": "6-8 Kasım", "track": "São Paulo", "isoDate": "2026-11-06", "status": "Bekliyor" },
            { "round": 22, "gp": "Las Vegas Grand Prix", "country": "ABD", "date": "19-21 Kasım", "track": "Las Vegas", "isoDate": "2026-11-19", "status": "Bekliyor" },
            { "round": 23, "gp": "Qatar Grand Prix", "country": "Katar", "date": "27-29 Kasım", "track": "Lusail", "isoDate": "2026-11-27", "status": "Bekliyor" },
            { "round": 24, "gp": "Abu Dhabi Grand Prix", "country": "Abu Dhabi", "date": "4-6 Aralık", "track": "Yas Marina", "isoDate": "2026-12-04", "status": "Bekliyor" }
        ],
        "resultsHistory": {
            "1": [
                { "pos": 1, "pilot": "George Russell #63", "team": "Mercedes-AMG Petronas F1 Team", "time": "1:23'06.801", "gap": "-", "pts": 25, "laps": 58, "fastest": true, "status": "Finished" },
                { "pos": 2, "pilot": "Andrea Kimi Antonelli #12", "team": "Mercedes-AMG Petronas F1 Team", "time": "1:23'09.775", "gap": "+2.974", "pts": 18, "laps": 58, "fastest": false, "status": "Finished" },
                { "pos": 3, "pilot": "Charles Leclerc #16", "team": "Scuderia Ferrari HP", "time": "1:23'22.320", "gap": "+15.519", "pts": 15, "laps": 58, "fastest": false, "status": "Finished" },
                { "pos": 4, "pilot": "Lewis Hamilton #44", "team": "Scuderia Ferrari HP", "time": "1:23'22.945", "gap": "+16.144", "pts": 12, "laps": 58, "fastest": false, "status": "Finished" },
                { "pos": 5, "pilot": "Lando Norris #1", "team": "McLaren Formula 1 Team", "time": "1:23'58.542", "gap": "+51.741", "pts": 10, "laps": 58, "fastest": false, "status": "Finished" },
                { "pos": 6, "pilot": "Max Verstappen #3", "team": "Oracle Red Bull Racing", "time": "1:24'01.418", "gap": "+54.617", "pts": 8, "laps": 58, "fastest": false, "status": "Finished" },
                { "pos": 7, "pilot": "Oliver Bearman #87", "team": "Haas F1 Team", "time": "1:23'11.394", "gap": "+1 Tur", "pts": 6, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 8, "pilot": "Arvid Lindblad #41", "team": "Visa Cash App RB F1 Team", "time": "1:23'18.617", "gap": "+1 Tur", "pts": 4, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 9, "pilot": "Gabriel Bortoleto #5", "team": "Audi F1 Team", "time": "1:23'19.576", "gap": "+1 Tur", "pts": 2, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 10, "pilot": "Pierre Gasly #10", "team": "BWT Alpine F1 Team", "time": "1:23'35.828", "gap": "+1 Tur", "pts": 1, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 11, "pilot": "Esteban Ocon #31", "team": "Haas F1 Team", "time": "1:23'36.651", "gap": "+1 Tur", "pts": 0, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 12, "pilot": "Alex Albon #23", "team": "Williams Racing", "time": "1:24'02.876", "gap": "+1 Tur", "pts": 0, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 13, "pilot": "Liam Lawson #30", "team": "Visa Cash App RB F1 Team", "time": "1:24'03.974", "gap": "+1 Tur", "pts": 0, "laps": 57, "fastest": false, "status": "Finished" },
                { "pos": 14, "pilot": "Franco Colapinto #43", "team": "BWT Alpine F1 Team", "time": "1:23'15.288", "gap": "+2 Tur", "pts": 0, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 15, "pilot": "Carlos Sainz Jr. #55", "team": "Williams Racing", "time": "1:23'43.687", "gap": "+2 Tur", "pts": 0, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 16, "pilot": "Sergio Perez #11", "team": "Cadillac F1 Team", "time": "1:23'14.651", "gap": "+3 Tur", "pts": 0, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": "NC", "pilot": "Lance Stroll #18", "team": "Aston Martin Aramco F1 Team", "time": "1:24'27.834", "gap": "+15 Tur", "pts": 0, "laps": 43, "fastest": false, "status": "NC" },
                { "pos": "DNF", "pilot": "Fernando Alonso #14", "team": "Aston Martin Aramco F1 Team", "time": "48'25.789", "gap": "+37 Tur", "pts": 0, "laps": 21, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Valtteri Bottas #77", "team": "Cadillac F1 Team", "time": "24'31.911", "gap": "+43 Tur", "pts": 0, "laps": 15, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Isack Hadjar #6", "team": "Oracle Red Bull Racing", "time": "14'25.525", "gap": "+48 Tur", "pts": 0, "laps": 10, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Oscar Piastri #81", "team": "McLaren Formula 1 Team", "time": "-", "gap": "DNF", "pts": 0, "laps": 0, "fastest": false, "status": "DNF" },
                { "pos": "DNS", "pilot": "Nico Hulkenberg #27", "team": "Audi F1 Team", "time": "-", "gap": "DNS", "pts": 0, "laps": 0, "fastest": false, "status": "DNS" }
            ],
            "2": [
                { "pos": 1, "pilot": "Andrea Kimi Antonelli #12", "team": "Mercedes-AMG F1 Team", "time": "1:33'15.607", "gap": "-", "pts": 25, "laps": 56, "fastest": true, "status": "Finished" },
                { "pos": 2, "pilot": "George Russell #63", "team": "Mercedes-AMG F1 Team", "time": "1:33'21.122", "gap": "+5.515", "pts": 18, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 3, "pilot": "Lewis Hamilton #44", "team": "Scuderia Ferrari HP", "time": "1:33'40.874", "gap": "+25.267", "pts": 15, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 4, "pilot": "Charles Leclerc #16", "team": "Scuderia Ferrari HP", "time": "1:33'44.501", "gap": "+28.894", "pts": 12, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 5, "pilot": "Oliver Bearman #87", "team": "Haas F1 Team", "time": "1:34'12.875", "gap": "+57.268", "pts": 10, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 6, "pilot": "Pierre Gasly #10", "team": "BWT Alpine F1 Team", "time": "1:34'15.254", "gap": "+59.647", "pts": 8, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 7, "pilot": "Liam Lawson #30", "team": "Visa Cash App RB F1 Team", "time": "1:34'36.195", "gap": "+1'20.588", "pts": 6, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 8, "pilot": "Isack Hadjar #6", "team": "Oracle Red Bull Racing", "time": "1:34'42.854", "gap": "+1'27.247", "pts": 4, "laps": 56, "fastest": false, "status": "Finished" },
                { "pos": 9, "pilot": "Carlos Sainz Jr. #55", "team": "Williams Racing", "time": "1:33'27.280", "gap": "+1 Tur", "pts": 2, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": 10, "pilot": "Franco Colapinto #43", "team": "BWT Alpine F1 Team", "time": "1:33'28.010", "gap": "+1 Tur", "pts": 1, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": 11, "pilot": "Nico Hulkenberg #27", "team": "Audi F1 Team", "time": "1:33'36.716", "gap": "+1 Tur", "pts": 0, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": 12, "pilot": "Arvid Lindblad #41", "team": "Visa Cash App RB F1 Team", "time": "1:33'38.435", "gap": "+1 Tur", "pts": 0, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": 13, "pilot": "Valtteri Bottas #77", "team": "Cadillac F1 Team", "time": "1:34'11.765", "gap": "+1 Tur", "pts": 0, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": 14, "pilot": "Esteban Ocon #31", "team": "Haas F1 Team", "time": "1:34'21.863", "gap": "+1 Tur", "pts": 0, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": 15, "pilot": "Sergio Perez #11", "team": "Cadillac F1 Team", "time": "1:34'30.248", "gap": "+1 Tur", "pts": 0, "laps": 55, "fastest": false, "status": "Finished" },
                { "pos": "DNF", "pilot": "Max Verstappen #3", "team": "Oracle Red Bull Racing", "time": "1:17'26.297", "gap": "+11 Tur", "pts": 0, "laps": 45, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Fernando Alonso #14", "team": "Aston Martin Aramco F1 Team", "time": "56'39.583", "gap": "+24 Tur", "pts": 0, "laps": 32, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Lance Stroll #18", "team": "Aston Martin Aramco F1 Team", "time": "15'19.929", "gap": "+47 Tur", "pts": 0, "laps": 8, "fastest": false, "status": "DNF" },
                { "pos": "DNS", "pilot": "Oscar Piastri #81", "team": "McLaren Formula 1 Team", "time": "-", "gap": "-", "pts": 0, "laps": 0, "fastest": false, "status": "DNS" },
                { "pos": "DNS", "pilot": "Lando Norris #1", "team": "McLaren Formula 1 Team", "time": "-", "gap": "-", "pts": 0, "laps": 0, "fastest": false, "status": "DNS" },
                { "pos": "DNS", "pilot": "Gabriel Bortoleto #5", "team": "Audi F1 Team", "time": "-", "gap": "-", "pts": 0, "laps": 0, "fastest": false, "status": "DNS" },
                { "pos": "DNS", "pilot": "Alexander Albon #23", "team": "Williams Racing", "time": "-", "gap": "-", "pts": 0, "laps": 0, "fastest": false, "status": "DNS" }
            ],
            "3": [
                { "pos": 1, "pilot": "Andrea Kimi Antonelli #12", "team": "Mercedes-AMG F1 Team", "time": "1:28'03.403", "gap": "-", "pts": 25, "laps": 53, "fastest": true, "status": "Finished" },
                { "pos": 2, "pilot": "Oscar Piastri #81", "team": "McLaren F1 Team", "time": "1:28'17.125", "gap": "+13.722", "pts": 18, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 3, "pilot": "Charles Leclerc #16", "team": "Scuderia Ferrari HP", "time": "1:28'18.673", "gap": "+15.270", "pts": 15, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 4, "pilot": "George Russell #63", "team": "Mercedes-AMG F1 Team", "time": "1:28'19.157", "gap": "+15.754", "pts": 12, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 5, "pilot": "Lando Norris #1", "team": "McLaren F1 Team", "time": "1:28'26.882", "gap": "+23.479", "pts": 10, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 6, "pilot": "Lewis Hamilton #44", "team": "Scuderia Ferrari HP", "time": "1:28'28.440", "gap": "+25.037", "pts": 8, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 7, "pilot": "Pierre Gasly #10", "team": "BWT Alpine F1 Team", "time": "1:28'35.743", "gap": "+32.340", "pts": 6, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 8, "pilot": "Max Verstappen #3", "team": "Oracle Red Bull Racing", "time": "1:28'36.080", "gap": "+32.677", "pts": 4, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 9, "pilot": "Liam Lawson #30", "team": "Visa Cash App RB F1 Team", "time": "1:28'53.583", "gap": "+50.180", "pts": 2, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 10, "pilot": "Esteban Ocon #31", "team": "BWT Alpine F1 Team", "time": "1:28'54.619", "gap": "+51.216", "pts": 1, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 11, "pilot": "Nico Hulkenberg #27", "team": "Audi F1 Team", "time": "1:28'55.683", "gap": "+52.280", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 12, "pilot": "Isack Hadjar #6", "team": "Oracle Red Bull Racing", "time": "1:28'59.557", "gap": "+56.154", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 13, "pilot": "Gabriel Bortoleto #5", "team": "Audi F1 Team", "time": "1:29'02.481", "gap": "+59.078", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 14, "pilot": "Arvid Lindblad #41", "team": "Visa Cash App RB F1 Team", "time": "1:29'03.251", "gap": "+59.848", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 15, "pilot": "Carlos Sainz Jr. #55", "team": "Williams Racing", "time": "1:29'08.411", "gap": "+1'05.008", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 16, "pilot": "Franco Colapinto #43", "team": "BWT Alpine F1 Team", "time": "1:29'09.176", "gap": "+1'05.773", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 17, "pilot": "Sergio Perez #11", "team": "Cadillac F1 Team", "time": "1:29'35.856", "gap": "+1'32.453", "pts": 0, "laps": 53, "fastest": false, "status": "Finished" },
                { "pos": 18, "pilot": "Fernando Alonso #14", "team": "Aston Martin Aramco F1 Team", "time": "1:28'29.951", "gap": "+1 Tur", "pts": 0, "laps": 52, "fastest": false, "status": "Finished" },
                { "pos": 19, "pilot": "Valtteri Bottas #77", "team": "Cadillac F1 Team", "time": "1:28'46.024", "gap": "+1 Tur", "pts": 0, "laps": 52, "fastest": false, "status": "Finished" },
                { "pos": 20, "pilot": "Alexander Albon #23", "team": "Williams Racing", "time": "1:28'08.470", "gap": "+2 Tur", "pts": 0, "laps": 51, "fastest": false, "status": "Finished" },
                { "pos": "DNF", "pilot": "Lance Stroll #18", "team": "Aston Martin Aramco F1 Team", "time": "52'49.430", "gap": "+23 Tur", "pts": 0, "laps": 30, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Oliver Bearman #87", "team": "Haas F1 Team", "time": "32'44.370", "gap": "+33 Tur", "pts": 0, "laps": 20, "fastest": false, "status": "DNF" }
            ]
        }
    },
    "motogp": {
        "news": [
            {
                "id": 1,
                "title": "DEV MARKALAR 2027 TESTLERİNİ TAMAMLADI: APRILIA’DA ŞİMDİLİK SES YOK!",
                "cat": "motogp",
                "date": "2026-04-14",
                "content": "MotoGP’de 2027 sezonuna hazırlıklar başlayarak, yeni teknik kurallara geçiş süreci iyice hız kazanmış durumda. KTM, Honda, Yamaha ve Ducati, 850cc motor konseptiyle geliştirdikleri prototip motosikletlerin testlerini tamamlayarak önemli bir aşamayı geride bıraktı.<br><br>Bilindiği üzere 2027 itibarıyla MotoGP’de 1000cc motorlar tarihe karışacak ve yerini 850cc makineler alacak. Bu değişim, takımların sadece motor performansını değil; aerodinami, ağırlık dağılımı ve yakıt verimliliği gibi birçok kritik unsuru yeniden düşünmesini gerektiriyor.<br><br>Testlerini tamamlayan üreticiler, pist üstünde topladıkları verilerle geliştirme sürecinde ciddi bir yol kat etmiş durumda. Özellikle Ducati’nin performans konusundaki iddialı yaklaşımı ve KTM’nin agresif geliştirme temposu öne çıkarken, Honda ile Yamaha’nın da son yıllardaki yeniden yapılanma sürecinde bu testlere büyük önem verdiği görülüyor.<br><br>Diğer yandan Aprilia tarafında henüz 850cc prototiple resmi bir test yapılmış değil. Bu durum, İtalyan üreticinin yeni döneme ne kadar hazır olduğu konusunda bazı soru işaretlerini de beraberinde getiriyor.",
                "img": "Resimler/MotoGP Haberler/Pirelli.jpg"
            }
        ],
        "pilots": [
            { "id": "bagnaia", "name": "Francesco Bagnaıa #63", "team": "Ducati Lenovo Team", "titles": 2, "img": "Resimler/MotoGP Pilot ve Takımlar/Francesco Bagnaia.png" },
            { "id": "marquez_m", "name": "Marc Márquez #93", "team": "Ducati Lenovo Team", "titles": 8, "img": "Resimler/MotoGP Pilot ve Takımlar/Marc Marquez.png" },
            { "id": "martin", "name": "Jorge Martín #89", "team": "Aprilia Racing", "titles": 1, "img": "Resimler/MotoGP Pilot ve Takımlar/Jorge Martin.png" },
            { "id": "bezzecchi", "name": "Marco Bezzecchı #72", "team": "Aprilia Racing", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Marco Bezzecchi.png" },
            { "id": "acosta", "name": "Pedro Acosta #37", "team": "Red Bull KTM Factory Racing", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Pedro Acosta.png" },
            { "id": "binder", "name": "Brad Bınder #33", "team": "Red Bull KTM Factory Racing", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Brad Binder.png" },
            { "id": "bastianini", "name": "Enea Bastıanını #23", "team": "Red Bull KTM Tech3", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Enea Bastianini.png" },
            { "id": "vinales", "name": "Maverıck Vıñales #12", "team": "Red Bull KTM Tech3", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Maverick Vinales.png" },
            { "id": "quartararo", "name": "Fabıo Quartararo #20", "team": "Monster Energy Yamaha MotoGP", "titles": 1, "img": "Resimler/MotoGP Pilot ve Takımlar/Fabio Quartararo.png" },
            { "id": "rins", "name": "Alex Rıns #42", "team": "Monster Energy Yamaha MotoGP", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Alex Rins.png" },
            { "id": "miller", "name": "Jack Mıller #43", "team": "Prima Pramac Yamaha MotoGP", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Jack Miller.png" },
            { "id": "marquez_a", "name": "Alex Márquez #73", "team": "BK8 Gresini Racing MotoGP", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Alex Marquez.png" },
            { "id": "aldeguer", "name": "Fermín Aldeguer #54", "team": "BK8 Gresini Racing MotoGP", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Fermin Aldeguer.png" },
            { "id": "diggia", "name": "Fabıo Dı Gıannantonıo #49", "team": "Pertamina Enduro VR46", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Fabio Di Giannantonio.png" },
            { "id": "morbidelli", "name": "Franco Morbıdellı #21", "team": "Pertamina Enduro VR46", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Franco Morbidelli.png" },
            { "id": "marini", "name": "Luca Marını #10", "team": "Repsol Honda Team", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Luca Marini.png" },
            { "id": "mir", "name": "Joan Mır #36", "team": "Repsol Honda Team", "titles": 1, "img": "Resimler/MotoGP Pilot ve Takımlar/Joan Mir.png" },
            { "id": "zarco", "name": "Johann Zarco #5", "team": "Castrol Honda LCR", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Johann Zarco.png" },
            { "id": "raul", "name": "Raul Fernández #25", "team": "Trackhouse Racing", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Raul Fernandez.png" },
            { "id": "ogura", "name": "Aı Ogura #79", "team": "Trackhouse Racing", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Ai Ogura.png" },
            { "id": "toprak", "name": "Toprak Razgatlıoğlu #7", "team": "Prima Pramac Yamaha MotoGP", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Toprak Razgatlıoğlu.png" }
        ],
        "teams": [
            { "id": "ducati", "name": "Ducatı Lenovo Team", "titles": 3, "img": "Resimler/MotoGP Pilot ve Takımlar/Ducati.png" },
            { "id": "aprilia", "name": "Aprılıa Racıng", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Aprilia.png" },
            { "id": "ktm", "name": "Red Bull KTM Factory Racıng", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/KTM.png" },
            { "id": "tech3", "name": "Red Bull KTM Tech3", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Tech3.png" },
            { "id": "yamaha", "name": "Monster Energy Yamaha MotoGP", "titles": 18, "img": "Resimler/MotoGP Pilot ve Takımlar/Monster Yamaha.png" },
            { "id": "pramac", "name": "Prıma Pramac Yamaha MotoGP", "titles": 1, "img": "Resimler/MotoGP Pilot ve Takımlar/Pramac Yamaha.png" },
            { "id": "gresini", "name": "BK8 Gresını Racıng MotoGP", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Gresini.png" },
            { "id": "vr46", "name": "Pertamına Enduro VR46", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/VR46.png" },
            { "id": "honda", "name": "Repsol Honda Team", "titles": 25, "img": "Resimler/MotoGP Pilot ve Takımlar/Repsol Honda.png" },
            { "id": "lcr", "name": "Castrol Honda LCR", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Honda LCR.png" },
            { "id": "trackhouse", "name": "Trackhouse Racıng", "titles": 0, "img": "Resimler/MotoGP Pilot ve Takımlar/Trackhouse.png" }
        ],
        "calendar": [
            { "round": 1, "gp": "Thailand Grand Prix", "country": "Tayland", "date": "27 Şubat-1 Mart", "track": "Buriram", "isoDate": "2026-02-27", "status": "Tamamlandı", "sessions": [{ "name": "Salı: 1. Antrenman", "time": "06:45" }, { "name": "Salı: Antrenman Seansı", "time": "11:00" }, { "name": "Çarşamba: Sıralama Turları 1", "time": "06:50" }, { "name": "Çarşamba: Sıralama Turları 2", "time": "11:00" }, { "name": "Çarşamba: Sprint Yarışı", "time": "11:00" }, { "name": "Cuma: Isınma Turları", "time": "06:40" }, { "name": "Cuma: Yarış", "time": "11:00" }] },
            { "round": 2, "gp": "Brazilian Grand Prix", "country": "Brezilya", "date": "18-20 Mart", "track": "Goiania", "isoDate": "2026-03-18", "status": "Tamamlandı", "sessions": [{ "name": "Cuma: 1. Antrenman", "time": "18:05" }, { "name": "Cuma: Ana Antrenman Seansı", "time": "22:00" }, { "name": "Cumartesi: 2.Antrenman Seansı", "time": "16:10" }, { "name": "Cumartesi: Sıralama Turları 1", "time": "16:50" }, { "name": "Cumartesi: Sıralama Turları 2", "time": "17:15" }, { "name": "Cumartesi: Sprint Yarışı", "time": "22:20" }, { "name": "Pazar: Isınma Turları", "time": "16:40" }, { "name": "Pazar: Yarış", "time": "21:00" }] },
            { "round": 3, "gp": "Americas Grand Prix", "country": "ABD", "date": "27-29 Mart", "track": "Austin", "isoDate": "2026-03-27", "status": "Tamamlandı", "sessions": [{ "name": "Pazartesi: 1. Antrenman", "time": "18:45" }, { "name": "Pazartesi: Ana Antrenman Seansı", "time": "23:00" }, { "name": "Salı: 2.Antrenman Seansı", "time": "18:10" }, { "name": "Salı: Sıralama Turları 1", "time": "18:50" }, { "name": "Salı: Sıralama Turları 2", "time": "18:15" }, { "name": "Salı: Sprint Yarışı", "time": "23:10" }, { "name": "Çarşamba: Isınma Turları", "time": "18:40" }, { "name": "Çarşamba: Yarış", "time": "23:00" }] },
            { "round": 4, "gp": "Spanish Grand Prix", "country": "İspanya", "date": "24-26 Nisan", "track": "Jerez – Ángel Nieto", "isoDate": "2026-04-24", "status": "Sıradaki", "sessions": [{ "name": "Cuma: 1. Antrenman", "time": "11:45" }, { "name": "Cuma: Ana Antrenman Seansı", "time": "16:00" }, { "name": "Cumartesi: 2.Antrenman Seansı", "time": "11:10" }, { "name": "Cumartesi: Sıralama Turları 1", "time": "11:50" }, { "name": "Cumartesi: Sıralama Turları 2", "time": "12:15" }, { "name": "Cumartesi: Sprint Yarışı", "time": "16:00" }, { "name": "Pazar: Isınma Turları", "time": "16:40" }, { "name": "Pazar: Yarış", "time": "15:00" }] },
            { "round": 5, "gp": "French Grand Prix", "country": "Fransa", "date": "8-10 Mayıs", "track": "Le Mans", "isoDate": "2026-05-08", "status": "Bekliyor", "sessions": [{ "name": "Cuma: 1. Antrenman", "time": "11:45" }, { "name": "Cuma: Ana Antrenman Seansı", "time": "16:00" }, { "name": "Cumartesi: 2.Antrenman Seansı", "time": "11:10" }, { "name": "Cumartesi: Sıralama Turları 1", "time": "11:50" }, { "name": "Cumartesi: Sıralama Turları 2", "time": "12:15" }, { "name": "Cumartesi: Sprint Yarışı", "time": "16:00" }, { "name": "Pazar: Isınma Turları", "time": "10:40" }, { "name": "Pazar: Yarış", "time": "15:00" }] },
            { "round": 6, "gp": "Catalunya Grand Prix", "country": "İspanya", "date": "15-17 Mayıs", "track": "Barcelona", "isoDate": "2026-05-15", "status": "Bekliyor" },
            { "round": 7, "gp": "Italian Grand Prix", "country": "İtalya", "date": "29-31 Mayıs", "track": "Mugello", "isoDate": "2026-05-29", "status": "Bekliyor" },
            { "round": 8, "gp": "Hungarian Grand Prix", "country": "Macaristan", "date": "5-7 Haziran", "track": "Balaton Park", "isoDate": "2026-06-05", "status": "Bekliyor" },
            { "round": 9, "gp": "Czechia Grand Prix", "country": "Çekya", "date": "19-21 Haziran", "track": "Brno", "isoDate": "2026-06-19", "status": "Bekliyor" },
            { "round": 10, "gp": "Dutch Tourist Trophy", "country": "Hollanda", "date": "26-28 Haziran", "track": "Assen", "isoDate": "2026-06-26", "status": "Bekliyor" },
            { "round": 11, "gp": "German Grand Prix", "country": "Almanya", "date": "10-12 Temmuz", "track": "Sachsenring", "isoDate": "2026-07-10", "status": "Bekliyor" },
            { "round": 12, "gp": "British Grand Prix", "country": "Birleşik Krallık", "date": "7-9 Ağustos", "track": "Silverstone", "isoDate": "2026-08-07", "status": "Bekliyor" },
            { "round": 13, "gp": "Aragon Grand Prix", "country": "İspanya", "date": "28-30 Ağustos", "track": "Aragon", "isoDate": "2026-08-28", "status": "Bekliyor" },
            { "round": 14, "gp": "San Marino Grand Prix", "country": "San Marino", "date": "11-13 Eylül", "track": "Misano", "isoDate": "2026-09-11", "status": "Bekliyor" },
            { "round": 15, "gp": "Austrian Grand Prix", "country": "Avusturya", "date": "18-20 Eylül", "track": "Spielberg", "isoDate": "2026-09-18", "status": "Bekliyor" },
            { "round": 16, "gp": "Japanese Grand Prix", "country": "Japonya", "date": "2-4 Ekim", "track": "Motegi", "isoDate": "2026-10-02", "status": "Bekliyor" },
            { "round": 17, "gp": "Indonesian Grand Prix", "country": "Endonezya", "date": "9-11 Ekim", "track": "Mandalika", "isoDate": "2026-10-09", "status": "Bekliyor" },
            { "round": 18, "gp": "Australian Grand Prix", "country": "Avustralya", "date": "23-25 Ekim", "track": "Phillip Island", "isoDate": "2026-10-23", "status": "Bekliyor" },
            { "round": 19, "gp": "Malaysian Grand Prix", "country": "Malezya", "date": "30 Ekim-1 Kasım", "track": "Sepang", "isoDate": "2026-10-30", "status": "Bekliyor" },
            { "round": 20, "gp": "Qatar Grand Prix", "country": "Katar", "date": "6-8 Kasım", "track": "Lusail", "isoDate": "2026-11-06", "status": "Bekliyor" },
            { "round": 21, "gp": "Portuguese Grand Prix", "country": "Portekiz", "date": "20-22 Kasım", "track": "Portimao", "isoDate": "2026-11-20", "status": "Bekliyor" },
            { "round": 22, "gp": "Valencia Grand Prix", "country": "İspanya", "date": "27-29 Kasım", "track": "Valencia", "isoDate": "2026-11-27", "status": "Bekliyor" }
        ],
        "resultsHistory": {
            "1": [
                { "pos": 1, "pilot": "Marco Bezzecchi #72", "team": "Aprilia Racing", "time": "39'36.270", "gap": "-", "pts": 25, "laps": 26, "fastest": true, "status": "Finished" },
                { "pos": 2, "pilot": "Pedro Acosta #37", "team": "Red Bull KTM Factory Racing", "time": "39'41.813", "gap": "+5.543", "pts": 20, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 3, "pilot": "Raul Fernandez #25", "team": "Trackhouse Racing", "time": "39'45.529", "gap": "+9.259", "pts": 16, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 4, "pilot": "Jorge Martin #89", "team": "Aprilia Racing", "time": "39'48.452", "gap": "+12.182", "pts": 13, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 5, "pilot": "Ai Ogura #79", "team": "Trackhouse Racing", "time": "39'48.681", "gap": "+12.411", "pts": 11, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 6, "pilot": "Fabio Di Giannantonio #49", "team": "Pertamina Enduro VR46 Racing Team", "time": "39'53.115", "gap": "+16.845", "pts": 10, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 7, "pilot": "Brad Binder #33", "team": "Red Bull KTM Factory Racing", "time": "39'53.633", "gap": "+17.363", "pts": 9, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 8, "pilot": "Franco Morbidelli #21", "team": "Pertamina Enduro VR46 Racing Team", "time": "39'54.497", "gap": "+18.227", "pts": 8, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 9, "pilot": "Francesco Bagnaia #63", "team": "Ducati Lenovo Team", "time": "39'54.610", "gap": "+18.340", "pts": 7, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 10, "pilot": "Luca Marini #10", "team": "Repsol Honda Team", "time": "39'55.371", "gap": "+19.101", "pts": 6, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 11, "pilot": "Johann Zarco #5", "team": "Castrol Honda LCR", "time": "39'56.173", "gap": "+19.903", "pts": 5, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 12, "pilot": "Enea Bastianini #23", "team": "Red Bull KTM Tech3", "time": "39'59.656", "gap": "+23.386", "pts": 4, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 13, "pilot": "Diogo Moreira #11", "team": "Castrol Honda LCR", "time": "40'00.956", "gap": "+24.686", "pts": 3, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 14, "pilot": "Fabio Quartararo #20", "team": "Monster Energy Yamaha MotoGP", "time": "40'07.093", "gap": "+30.823", "pts": 2, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 15, "pilot": "Alex Rins #42", "team": "Monster Energy Yamaha MotoGP", "time": "40'09.225", "gap": "+32.955", "pts": 1, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 16, "pilot": "Maverick Viñales #12", "team": "Red Bull KTM Tech3", "time": "40'12.815", "gap": "+36.545", "pts": 0, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 17, "pilot": "Toprak Razgatlıoğlu #7", "team": "Prima Pramac Racing", "time": "40'15.464", "gap": "+39.194", "pts": 0, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 18, "pilot": "Jack Miller #43", "team": "Prima Pramac Racing", "time": "40'24.118", "gap": "+47.848", "pts": 0, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": 19, "pilot": "Michele Pirro #51", "team": "BK8 Gresini Racing Team", "time": "40'39.868", "gap": "+1'03.598", "pts": 0, "laps": 26, "fastest": false, "status": "Finished" },
                { "pos": "DNF", "pilot": "Joan Mir #36", "team": "Repsol Honda Team", "time": "36'04.638", "gap": "+3 Tur", "pts": 0, "laps": 23, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Alex Marquez #73", "team": "BK8 Gresini Racing Team", "time": "32'38.163", "gap": "+5 Tur", "pts": 0, "laps": 21, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Marc Marquez #93", "team": "Ducati Lenovo Team", "time": "31'11.314", "gap": "+6 Tur", "pts": 0, "laps": 20, "fastest": false, "status": "DNF" }
            ],
            "2": [
                { "pos": 1, "pilot": "Marco Bezzecchi #72", "team": "Aprilia Racing", "time": "30'19.760", "gap": "-", "pts": 25, "laps": 23, "fastest": true, "status": "Finished" },
                { "pos": 2, "pilot": "Jorge Martin #89", "team": "Aprilia Racing", "time": "30'22.991", "gap": "+3.231", "pts": 20, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 3, "pilot": "Fabio Di Giannantonio #49", "team": "Pertamina Enduro VR46", "time": "30'23.540", "gap": "+3.780", "pts": 16, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 4, "pilot": "Marc Márquez #93", "team": "Ducati Lenovo Team", "time": "30'23.849", "gap": "+4.089", "pts": 13, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 5, "pilot": "Ai Ogura #79", "team": "Trackhouse Racing", "time": "30'28.163", "gap": "+8.403", "pts": 11, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 6, "pilot": "Alex Márquez #73", "team": "BK8 Gresini Racing Team", "time": "30'28.678", "gap": "+8.918", "pts": 10, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 7, "pilot": "Pedro Acosta #37", "team": "Red Bull KTM Factory Racing", "time": "30'30.447", "gap": "+10.687", "pts": 9, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 8, "pilot": "Fermín Aldeguer #54", "team": "BK8 Gresini Racing Team", "time": "30'31.119", "gap": "+11.359", "pts": 8, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 9, "pilot": "Johann Zarco #5", "team": "Castrol Honda LCR", "time": "30'32.667", "gap": "+12.907", "pts": 7, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 10, "pilot": "Raul Fernandez #25", "team": "Trackhouse Racing", "time": "30'36.130", "gap": "+16.370", "pts": 6, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 11, "pilot": "Luca Marini #10", "team": "Repsol Honda Team", "time": "30'38.289", "gap": "+18.529", "pts": 5, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 12, "pilot": "Franco Morbidelli #21", "team": "Pertamina Enduro VR46", "time": "30'39.740", "gap": "+19.980", "pts": 4, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 13, "pilot": "Diogo Moreira #11", "team": "Castrol Honda LCR", "time": "30'41.082", "gap": "+21.322", "pts": 3, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 14, "pilot": "Alex Rins #42", "team": "Monster Energy Yamaha MotoGP", "time": "30'42.459", "gap": "+22.699", "pts": 2, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 15, "pilot": "Enea Bastianini #23", "team": "Red Bull KTM Tech3", "time": "30'43.600", "gap": "+23.840", "pts": 1, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 16, "pilot": "Fabio Quartararo #20", "team": "Monster Energy Yamaha MotoGP", "time": "30'46.163", "gap": "+26.403", "pts": 0, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 17, "pilot": "Toprak Razgatlıoğlu #7", "team": "Prima Pramac Racing", "time": "30'50.047", "gap": "+30.287", "pts": 0, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": 18, "pilot": "Maverick Viñales #12", "team": "Red Bull KTM Tech3", "time": "30'56.157", "gap": "+36.397", "pts": 0, "laps": 23, "fastest": false, "status": "Finished" },
                { "pos": "DNF", "pilot": "Joan Mir #36", "team": "Repsol Honda Team", "time": "13'18.148", "gap": "+13 Tur", "pts": 0, "laps": 13, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Francesco Bagnaia #63", "team": "Ducati Lenovo Team", "time": "13'21.365", "gap": "+13 Tur", "pts": 0, "laps": 1, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Brad Binder #33", "team": "Red Bull KTM Factory Racing", "time": "4'07.100", "gap": "+20 Tur", "pts": 0, "laps": 10, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Jack Miller #43", "team": "Prima Pramac Racing", "time": "1'27.660", "gap": "+22 Tur", "pts": 0, "laps": 3, "fastest": false, "status": "DNF" }
            ],
            "3": [
                { "pos": 1, "pilot": "Marco Bezzecchi #72", "team": "Aprilia Racing", "time": "40'50.653", "gap": "-", "pts": 25, "laps": 20, "fastest": true, "status": "Finished" },
                { "pos": 2, "pilot": "Jorge Martín #89", "team": "Aprilia Racing", "time": "40'52.689", "gap": "+2.036", "pts": 20, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 3, "pilot": "Pedro Acosta #37", "team": "Red Bull KTM Factory Racing", "time": "40'55.150", "gap": "+4.497", "pts": 16, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 4, "pilot": "Fabio Di Giannantonio #49", "team": "Pertamina Enduro VR46", "time": "40'57.625", "gap": "+6.972", "pts": 13, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 5, "pilot": "Marc Márquez #93", "team": "Ducati Lenovo Team", "time": "40'58.753", "gap": "+8.100", "pts": 11, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 6, "pilot": "Enea Bastianini #23", "team": "Red Bull KTM Tech3", "time": "40'58.896", "gap": "+8.243", "pts": 10, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 7, "pilot": "Alex Márquez #73", "team": "BK8 Gresini Racing Team", "time": "41'01.906", "gap": "+11.253", "pts": 9, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 8, "pilot": "Raul Fernandez #25", "team": "Trackhouse Racing", "time": "41'03.782", "gap": "+13.129", "pts": 8, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 9, "pilot": "Luca Marini #10", "team": "Repsol Honda Team", "time": "41'05.124", "gap": "+14.471", "pts": 7, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 10, "pilot": "Francesco Bagnaia #63", "team": "Ducati Lenovo Team", "time": "41'05.197", "gap": "+14.544", "pts": 6, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 11, "pilot": "Fermin Aldeguer #54", "team": "BK8 Gresini Racing Team", "time": "41'11.716", "gap": "+21.063", "pts": 5, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 12, "pilot": "Brad Binder #33", "team": "Red Bull KTM Factory Racing", "time": "41'12.715", "gap": "+22.062", "pts": 4, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 13, "pilot": "Diogo Moreira #11", "team": "Castrol Honda LCR", "time": "41'12.854", "gap": "+22.201", "pts": 3, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 14, "pilot": "Franco Morbidelli #21", "team": "Pertamina Enduro VR46", "time": "41'15.024", "gap": "+24.371", "pts": 2, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 15, "pilot": "Toprak Razgatlıoğlu #7", "team": "Prima Pramac Racing", "time": "41'16.202", "gap": "+25.549", "pts": 1, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 16, "pilot": "Jack Miller #43", "team": "Prima Pramac Racing", "time": "41'16.962", "gap": "+26.309", "pts": 0, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 17, "pilot": "Fabio Quartararo #20", "team": "Monster Energy Yamaha MotoGP", "time": "41'17.789", "gap": "+27.136", "pts": 0, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": 18, "pilot": "Alex Rins #42", "team": "Monster Energy Yamaha MotoGP", "time": "41'29.354", "gap": "+38.701", "pts": 0, "laps": 20, "fastest": false, "status": "Finished" },
                { "pos": "DNF", "pilot": "Johann Zarco #5", "team": "Castrol Honda LCR", "time": "38'51.967", "gap": "+2 Tur", "pts": 0, "laps": 18, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Ai Ogura #79", "team": "Trackhouse Racing", "time": "31'23.220", "gap": "+5 Tur", "pts": 0, "laps": 11, "fastest": false, "status": "DNF" },
                { "pos": "DNF", "pilot": "Joan Mir #36", "team": "Repsol Honda Team", "time": "10'16.273", "gap": "+15 Tur", "pts": 0, "laps": 5, "fastest": false, "status": "DNF" }
            ]
        },
        "standings": {
            "pilots": [
                { "pos": 1, "name": "Marco Bezzecchi #72", "team": "Aprilia Racing", "pts": 81 },
                { "pos": 2, "name": "Jorge Martin #89", "team": "Aprilia Racing", "pts": 77 },
                { "pos": 3, "name": "Pedro Acosta #37", "team": "Red Bull KTM Factory Racing", "pts": 60 },
                { "pos": 4, "name": "Fabio Di Giannantonio #49", "team": "Pertamina Enduro VR46", "pts": 50 },
                { "pos": 5, "name": "Marc Marquez #93", "team": "Ducati Lenovo Team", "pts": 45 },
                { "pos": 6, "name": "Raul Fernandez #25", "team": "Trackhouse MotoGP Team", "pts": 40 },
                { "pos": 7, "name": "Ai Ogura #79", "team": "Trackhouse MotoGP Team", "pts": 37 },
                { "pos": 8, "name": "Alex Marquez #73", "team": "BK8 Gresini Racing MotoGP", "pts": 28 },
                { "pos": 9, "name": "Francesco Bagnaia #63", "team": "Ducati Lenovo Team", "pts": 25 },
                { "pos": 10, "name": "Luca Marini #10", "team": "Repsol Honda Team", "pts": 23 },
                { "pos": 11, "name": "Enea Bastianini #23", "team": "Red Bull KTM Tech3", "pts": 22 },
                { "pos": 12, "name": "Brad Binder #33", "team": "Red Bull KTM Factory Racing", "pts": 17 },
                { "pos": 13, "name": "Franco Morbidelli #21", "team": "Pertamina Enduro VR46 Racing Team", "pts": 14 },
                { "pos": 14, "name": "Fermin Aldeguer #54", "team": "BK8 Gresini Racing MotoGP", "pts": 13 },
                { "pos": 15, "name": "Johann Zarco #5", "team": "Castrol Honda LCR", "pts": 13 },
                { "pos": 16, "name": "Diogo Moreira #11", "team": "Pro Honda LCR", "pts": 9 },
                { "pos": 17, "name": "Fabio Quartararo #20", "team": "Monster Energy Yamaha MotoGP Team", "pts": 6 },
                { "pos": 18, "name": "Alex Rins #42", "team": "Monster Energy Yamaha MotoGP Team", "pts": 3 },
                { "pos": 19, "name": "Joan Mir #36", "team": "Repsol Honda Team", "pts": 3 },
                { "pos": 20, "name": "Toprak Razgatlıoğlu #7", "team": "Prima Pramac Yamaha MotoGP", "pts": 1 },
                { "pos": 21, "name": "Jack Miller #43", "team": "Prima Pramac Yamaha MotoGP", "pts": 0 },
                { "pos": 22, "name": "Maverick Viñales #12", "team": "Red Bull KTM Tech3", "pts": 0 },
                { "pos": 23, "name": "Michele Pirro #51", "team": "BK8 Gresini Racing MotoGP", "pts": 0 }
            ],
            "teams": [
                { "pos": 1, "name": "Aprilia Racing", "pts": 158 },
                { "pos": 2, "name": "Red Bull KTM Factory Racing", "pts": 77 },
                { "pos": 3, "name": "Trackhouse Racing", "pts": 77 },
                { "pos": 4, "name": "Ducati Team", "pts": 70 },
                { "pos": 5, "name": "Pertamina Enduro VR46", "pts": 64 },
                { "pos": 6, "name": "BK8 Gresini Racing MotoGP", "pts": 41 },
                { "pos": 7, "name": "Pro Honda LCR", "pts": 23 },
                { "pos": 8, "name": "Honda HRC Castrol", "pts": 18 },
                { "pos": 9, "name": "Red Bull KTM Tech3", "pts": 11 },
                { "pos": 10, "name": "Monster Energy Yamaha MotoGP Team", "pts": 9 },
                { "pos": 11, "name": "Prima Pramac Yamaha MotoGP", "pts": 1 },
            ]
        }
    },
    "haberler": {
        "news": [
            {
                "id": 1,
                "title": "TÜRKİYE OFFROAD ŞAMPİYONASI’NIN İLK AYAĞI TAMAMLANDI!",
                "cat": "haberler",
                "date": "2026-04-14",
                "content": "2026 Türkiye Offroad Şampiyonası’nın ilk ayağı, Trabzon’da yoğun katılımla gerçekleştirildi.<br><br>Yoğun sis ve zaman zaman karın yerini yağmura bırakmasıyla daha da zorlaşan etaplarda, otomobil kategorisinde Şehmuz Oğuz üstün bir performans sergileyerek zirvede yer aldı. Onu Ahmet Köse ve ev sahibi Erdinç Türkmen takip etti.<br><br>SSV kategorisinde ise tüm zorluklara rağmen istikrarlı bir performans ortaya koyan Eren Alver birinciliği elde ederken, Ergün Çirkin ikinci, Adem Kalyon ise üçüncü sırada yer aldı.<br><br>Türkiye Offroad Şampiyonası, 9-10 Mayıs tarihlerinde Kahramanmaraş’ta tüm heyecanıyla devam edecek.",
                "img": "Resimler/Haberler/Offroad.png"
            }
        ]
    },
    "milli sporcularımız": {
        "news": [
            {
                "id": 1,
                "title": "AYHANCAN GÜVEN, WEC'TE İLK YARIŞINA ÇIKIYOR!",
                "cat": "milli sporcularımız",
                "date": "2026-04-05",
                "content": "Türkiye'nin gururu Ayhancan Güven, Dünya Dayanıklılık Şampiyonası'ndaki ilk yarışına çıkıyor! 19 Nisan tarihinde 6 HOURS IMOLA yarışı ile Porsche LMGT3 sınıfında mücadele edecek. Milli sporcumuza başarılar dileriz!",
                "img": "Resimler/Milli Sporcularımız Haberler/Ayhancan Güven.jpg"
            }
        ],
        "pilots": [
            { "id": "miras", "name": "Ali Fuat Miras", "team": "Dynamic Racing Team (Karting Junior)" },
            { "id": "türkkan", "name": "Ali Türkkan", "team": "Castrol Ford Team Türkiye (Ralli)" },
            { "id": "aksoy", "name": "Alp Hasan Aksoy", "team": "Prema Racing (F4)" },
            { "id": "birinci", "name": "Ateş Birinci", "team": "Emre Ergör Karting Team (Karting Senior)" },
            { "id": "güven", "name": "Ayhancan Güven", "team": "Manthey Racing (WEC)" },
            { "id": "çebi", "name": "Ayşe Çebi", "team": "Borusan Otomotiv Motorsport Karting Team (Karting Senior)" },
            { "id": "biter", "name": "Aytaç Biter", "team": "Borusan Otomotiv Motorsport Karting Team (Karting Master)" },
            { "id": "gücenmez", "name": "Bahadır Gücenmez", "team": "Skoda Fabia Rally2 EVO (Ralli)" },
            { "id": "yıldırım", "name": "Batı Ege Yıldırım", "team": "Dynamic Racing Team (Karting Junior)" },
            { "id": "zülfikari", "name": "İskender Zülfikari", "team": "KR Motorsport (OK-Junior)" },
            { "id": "bayındır", "name": "Berke Bayındır", "team": "Volkswagen Motorsport Turkey (Scirocco R-Cup Europe)" },
            { "id": "korkmaz", "name": "Burçin Korkmaz", "team": "Toksport WRT (Ralli)" },
            { "id": "çetinkaya", "name": "Burcu Çetinkaya", "team": "GP Garage My Team (Ralli)" },
            { "id": "erkal", "name": "Can Erkal", "team": "Castrol Ford Team Türkiye (Ralli)" },
            { "id": "ünsal", "name": "Can Luca Ünsal", "team": "Bursa Otomobil Sporları Kulübü (Karting Junior)" },
            { "id": "özler", "name": "Can Özler", "team": "Dynamic Racing Team (Karting Junior)" },
            { "id": "bölükbaşı", "name": "Cem Bölükbaşı", "team": "Nielsen Racing (European Le Mans Series)" },
            { "id": "oğuzhan", "name": "Cengiz Oğuzhan", "team": "Porsche GT3 Cup Challenge Benelux" },
            { "id": "ceyişakar", "name": "Cenk Ceyişakar", "team": "Porsche GT3 Cup Challenge Benelux" },
            { "id": "güney", "name": "Çiçek Güney", "team": "Castrol Ford Team Türkiye (Ralli)" },
            { "id": "sağım", "name": "Demir Sağım", "team": "Dynamic Racing Team (Karting Junior)" },
            { "id": "şairoğlu", "name": "Efe Şairoğlu", "team": "Borusan Otomotiv Motorsport Karting Team (Karting Junior)" },
            { "id": "kalafatoğlu", "name": "Emir Kalafatoğlu", "team": "Borusan Otomotiv Motorsport (GT4 European Series)" },
            { "id": "tanju", "name": "Emir Tanju", "team": "Borusan Otomotiv Motorsport Karting Team (Karting Senior)" },
            { "id": "yurdakul", "name": "Emre Yurdakul", "team": "GP Garage My Team (Ralli)" },
            { "id": "ünlüdoğan", "name": "Erin Ünlüdoğan", "team": "Borusan Otomotiv Motorsport Karting Team (Karting Junior)" },
            { "id": "yücesan", "name": "Ersin Yücesan", "team": "PROsport Racing (Almanya Nürburgring Dayanıklılık Serisi)" },
            { "id": "ayhan", "name": "Fatih Ayhan", "team": "Borusan Otomotiv Motorsport (GT4 Avrupa Serisi ve Türkiye Pist Şampiyonası)" },
            { "id": "atar", "name": "Galip Atar", "team": "Octane 126 ve Ülkü Motorsport (Ferrari Challenge Dünya Şampiyonası)" },
            { "id": "taşdelen", "name": "Gün Taşdelen", "team": "Borusan Otomotiv Motorsport Karting Team (Karting Junior)" },
            { "id": "okyay", "name": "İbrahim Okyay", "team": "Borusan Otomotiv Motorsport (GT4 Avrupa Serisi)" },
            { "id": "gürgenç", "name": "Kaan Gürgenç", "team": "Borusan Otomotiv Motorsport (Türkiye Pist Şampiyonası)" },
            { "id": "önder", "name": "Kaan Önder", "team": "Borusan Otomotiv Motorsport (e-spor Sim Racing)" },
            { "id": "özşenler", "name": "Kaan Özşenler", "team": "Lassa Rally Team, Castrol Ford Team Türkiye ve Fiat (Birmot) (Ralli)" },
            { "id": "kazaz", "name": "Kerem Kazaz", "team": "Team Petrol Ofisi (Ralli)" },
            { "id": "sulyak", "name": "Kerim Sulyak", "team": "Dynamic Racing Team (Karting Senior)" },
            { "id": "kocabıyık", "name": "Levent Kocabıyık", "team": "Borusan Otomotiv Motorsport (Türkiye Pist Şampiyonası)" },
            { "id": "sulyak", "name": "Leyla Sulyak", "team": "Dynamic Racing Team (Karting Senior)" },
            { "id": "becce", "name": "Mert Becce", "team": "Becce Motorsports / Rally Raid Team Turkey (Off-Road)" },
            { "id": "dalkıran", "name": "Mert Dalkıran", "team": "Comer Top Kart Junior Team (Karting)" },
            { "id": "bostancı", "name": "Murat Bostancı", "team": "Castrol Ford Team Türkiye (Ralli)" },
            { "id": "kolot", "name": "Ömer Asaf Kolot", "team": "Bosphorus Racing / TOSFED National Team Turkey (Karting)" },
            { "id": "vatansever", "name": "Onur Vatansever", "team": "GP Garage My Team (Ralli)" },
            { "id": "avcıoğlu", "name": "Orhan Avcıoğlu", "team": "Toksport WRT (Ralli)" },
            { "id": "tatar", "name": "Sertaç Tatar", "team": "GE Rally Raid Team (Off-Road)" },
            { "id": "razgatlıoğlu", "name": "Toprak Razgatlıoğlu", "team": "Prima Pramac Yamaha Racing (MotoGP)" },
            { "id": "ülkü", "name": "Ümit Ülkü", "team": "Ülkü Motorsport (Türkiye Pist Şampiyonası)" },
            { "id": "ışık", "name": "Volkan Işık", "team": "GP Garage My Team (Ralli)" },
            { "id": "oskan", "name": "Yadel Oskan", "team": "Yadel Oskan Motorsport (Porsche GT3 Cup Challenge Eastern Europe)" },
            { "id": "avcı", "name": "Yağız Avcı", "team": "Castrol Ford Team Türkiye (Ralli)" },
            { "id": "birinci", "name": "Yağız Birinci", "team": "Yağız Birinci Motorsport (Off-Road)" },
            { "id": "gedik", "name": "Yağız Gedik", "team": "Borusan Otomotiv Motorsport (GT4 European Series)" },
            { "id": "çetin", "name": "Yiğit Çetin", "team": "Dynamic Racing Team (Karting Mini)" },
            { "id": "çukurova", "name": "Zeynep Çukurova", "team": "BC Vision Motorsport (Karting Senior)" }
        ],
    }
};

const CIRCUITS_DB = {
    "Sakhir": {
        "len": "5.412 km", "turns": "15", "drs": "3 Bölgeli", "record": "1:31.447 (Pedro de la Rosa)",
        "opened": "2004", "firstWinner": "Michael Schumacher (2004)",
        "mostWinsPilot": "Lewis Hamilton (5 Galibiyet)", "mostWinsTeam": "Ferrari (7 Galibiyet)",
        "description": "Bahreyn Uluslararası Pisti (Sakhir), 2004 yılında açılan ve Orta Doğu'daki ilk Formula 1 yarışı olan Sakhir'de düzenlenen bir yarış pistidir."
    },
    "Suzuka": {
        "len": "5.807 km", "turns": "18", "drs": "1 Bölge", "record": "1:30.983 (Lewis Hamilton)",
        "opened": "1962", "firstWinner": "Gerhard Berger (1987)",
        "mostWinsPilot": "Michael Schumacher (6 Galibiyet)", "mostWinsTeam": "McLaren (9 Galibiyet)",
        "description": "Efsanevi '8' şekilli pist yapısıyla Suzuka, hem pilotlar hem de taraftarlar için takvimin en teknik ve sevilen duraklarından biridir."
    },
    "Melbourne": {
        "len": "5.278 km", "turns": "14", "drs": "4 Bölge", "record": "1:20.235 (Max Verstappen)",
        "opened": "1996", "firstWinner": "Damon Hill (1996)",
        "mostWinsPilot": "Michael Schumacher (4 Galibiyet)", "mostWinsTeam": "McLaren (11 Galibiyet)",
        "description": "Albert Park'ta düzenlenen Avustralya GP, sokak pisti karakteriyle sezonun her zaman heyecan verici başlangıç noktalarından biridir."
    },
    "Shanghai": {
        "len": "5.451 km", "turns": "16", "drs": "2 Bölge", "record": "1:32.238 (Michael Schumacher)",
        "opened": "2004", "firstWinner": "Rubens Barrichello (2004)",
        "mostWinsPilot": "Lewis Hamilton (6 Galibiyet)", "mostWinsTeam": "Mercedes (6 Galibiyet)",
        "description": "Şekil olarak 'Shang' (Yukarı) karakterini andıran Çin GP pisti, devasa ana tribünü ve uzun düzlükleriyle tanınır."
    },
    "Lusail": {
        "len": "5.419 km", "turns": "16", "drs": "1 Bölge", "record": "1:24.319 (Max Verstappen)",
        "opened": "2004", "firstWinner": "Lewis Hamilton (2021) / Sete Gibernau (MotoGP 2004)",
        "mostWinsPilot": "Marc Márquez (MotoGP - 2 Galibiyet)", "mostWinsTeam": "Yamaha (MotoGP - 10 Galibiyet)",
        "description": "Katar'daki Lusail pisti, gece aydınlatması altında düzenlenen yarışlarıyla hem F1 hem de MotoGP takvimlerine ihtişam katar."
    },
    "Imola": {
        "len": "4.909 km", "turns": "19", "drs": "1 Bölge", "record": "1:15.484 (Lewis Hamilton)",
        "opened": "1953", "firstWinner": "Nelson Piquet (1980)",
        "mostWinsPilot": "Michael Schumacher (7 Galibiyet)", "mostWinsTeam": "Ferrari (8 Galibiyet)",
        "description": "Autodromo Enzo e Dino Ferrari, İtalya'nın motor sporları kalbinde yer alan klasik ve dar yapılı efsanevi bir pisttir."
    },
    "Miami": {
        "len": "5.412 km", "turns": "19", "drs": "3 Bölge", "record": "1:29.708 (Max Verstappen)",
        "opened": "2022", "firstWinner": "Max Verstappen (2022)",
        "mostWinsPilot": "Max Verstappen (3 Galibiyet)", "mostWinsTeam": "Red Bull (3 Galibiyet)",
        "description": "Hard Rock Stadyumu çevresindeki Miami International Autodrome, modern F1'in eğlence ve hızı birleştiren ikonik duraklarından biridir."
    },
    "Jeddah": {
        "len": "6.174 km", "turns": "27", "drs": "3 Bölge", "record": "1:30.734 (Lewis Hamilton)",
        "opened": "2021", "firstWinner": "Lewis Hamilton (2021)",
        "mostWinsPilot": "Max Verstappen (2 Galibiyet)", "mostWinsTeam": "Red Bull (2 Galibiyet)",
        "description": "Dünyanın en hızlı sokak pisti olan Corniche Pisti, Kızıldeniz kıyısındaki dar yapısı ve yüksek hızıyla pilotların sınırlarını zorlar."
    },
    "Martinsville": {
        "len": "0.847 km", "turns": "4", "drs": "Yok", "record": "18.746s (Joey Logano)",
        "opened": "1947", "firstWinner": "Red Byron (1949)",
        "mostWinsPilot": "Richard Petty (15 Galibiyet)", "mostWinsTeam": "Hendrick Motorsports (28 Galibiyet)",
        "description": "NASCAR'ın en kısa ama en heyecan verici pistlerinden biri olan 'The Paperclip', her virajda aksiyon vaat eden bir klasik."
    },
    "Long Beach": {
        "len": "3.167 km", "turns": "11", "drs": "Yok", "record": "1:05.309 (Colton Herta)",
        "opened": "1975", "firstWinner": "Clay Regazzoni (F1 1976)",
        "mostWinsPilot": "Al Unser Jr (6 Galibiyet)", "mostWinsTeam": "Penske (11 Galibiyet)",
        "description": "Kaliforniya'nın ikonik sahil şeridinde düzenlenen Long Beach, IndyCar takviminin en prestijli sokak yarışlarından biridir."
    },
    "Zagreb": {
        "len": "Varyantlar", "turns": "-", "drs": "Yok", "record": "-",
        "opened": "2021 (WRC)", "firstWinner": "Sébastien Ogier (2021)",
        "mostWinsPilot": "Sébastien Ogier (2 Galibiyet)", "mostWinsTeam": "Toyota (3 Galibiyet)",
        "description": "Hırvatistan Rallisi, Zagreb çevresindeki dar ve değişken asfalt etaplarıyla WRC'nin en zorlu asfalt mücadelelerinden biridir."
    },
    "Jerez – Ángel Nieto": {
        "len": "4.428 km", "turns": "13", "drs": "Yok", "record": "1:36.168 (Francesco Bagnaia)",
        "opened": "1987", "firstWinner": "Wayne Gardner (1987)",
        "mostWinsPilot": "Valentino Rossi (9 Galibiyet)", "mostWinsTeam": "Honda (22 Galibiyet)",
        "description": "İspanya’nın güneşi altında parlayan Jerez - Ángel Nieto pisti, MotoGP takviminin en ikonik ve teknik duraklarından biridir."
    },
};

const TRACK_STATS = CIRCUITS_DB["Jerez – Ángel Nieto"];

// Dinamik veriler script.js tarafından güncellenecektir.
let CURRENT_WEEKEND_DATA = null;
let CURRENT_TRACK_STATS = null;
